[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]
preview = ["pixi-build"]

[tasks]
opencv_demo = "opencv_demo"
opencv_demo_ci = "opencv_demo --no-display"

[dependencies]
my_package = { path = "." }

[package]
name = "my_package"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-cmake"
version = "*"

[package.host-dependencies]
libopencv = ">=4.12, <5.0"
libcurl = ">=8.14.1, <9.0"

